# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: >-
  Be direct and technical. Focus on correctness, performance, and idiomatic
  Go patterns. Flag issues clearly without excessive praise.

reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  commit_status: true
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  poem: false
  review_status: true
  suggested_labels: true
  suggested_reviewers: true
  auto_apply_labels: false
  auto_assign_reviewers: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DRAFT"
      - "[WIP]"
      - "[DRAFT]"

  path_filters:
    - "!vendor/**"
    - "!**/vendor/**"
    - "!**/generated/**"
    - "!**/*.pb.go"
    - "!**/mock/**"
    - "!go.sum"

  # Exceptions to CLAUDE.md rules (which is auto-applied via knowledge_base.code_guidelines)
  path_instructions:
    - path: "**/*_test.go"
      instructions: |
        Test code exceptions: long functions and raw string literals are acceptable.
        Focus on test coverage, assertion quality, and Arrange-Act-Assert pattern.
        Verify table-driven tests use t.Parallel() and subtests use t.Parallel().
        Flag shared mutable state between parallel tests.
        Ensure require is used for error checks, assert for value checks.

    - path: "pkg/**/*.go"
      instructions: |
        Public API surface. Review for:
        - Backwards compatibility (breaking changes to exported types/functions)
        - Clear, stable interfaces with doc comments on all exports
        - Sentinel errors for expected failure modes
        - No leaking of internal types

    - path: "internal/**/*.go"
      instructions: |
        Internal implementation. Focus on:
        - Error wrapping with context (fmt.Errorf("...: %w", err))
        - Proper context.Context propagation and cancellation
        - Goroutine lifecycle (errgroup usage, channel ownership)
        - No "failed" or "error" in error wrap strings

    - path: "cmd/**/*.go"
      instructions: |
        CLI entry point. Check for:
        - Clean flag definitions and usage strings
        - Proper error propagation to ExitErrHandler
        - No business logic leaking into CLI layer

  tools:
    actionlint:
      enabled: true
    golangci-lint:
      enabled: true
      config_file: ".golangci.yaml"
    semgrep:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    languagetool:
      enabled: true
      level: default
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    trivy:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: local
  code_guidelines:
    enabled: true
    filePatterns:
      - "CLAUDE.md"
      - "CONTRIBUTING.md"
